### ISSUE TITLE
Unable to find IP address

### ISSUE THREAD

**Issue by DuelistRag3** [Lan2Play/eventula-manager#878]
So when i follow the tutorial from the docs i get the following error:
```
error="service \"myservice\" error: unable to find IP address for the container \"/eventula_manager_app/": the server is ingored
```
with portainer i observed that the app service does not join bridge network nor getting an ip address in the eventula_default

**Comment by Apfelwurm** [comment]
Hey, at first, i have never used portainer, so i currently don't know the specifics of it.
Please provide more information, so we can find out what is wrong.
How did you set up eventula in portainer step by step? 
What is myservice?
What bridge network are you talking about? (the eventula container is not built to be directly exposed to the internet, even though it should be possible, but not recommended)
Is your machine online or offline?
how does your compose (if used) look like?
how does your env look like? (ofc with replaced passwords)
what is the eventula container logging?
how long did you wait after the startup?

Have a great day!

PS: Maybe consider joining our Discord (https://discord.gg/zF5C9WPWFq) for a more direct support experience

**Comment by DuelistRag3** [comment]
Hi,
to be more clear, for the setup of eventula itself i used the compose and .env file from your documentation via the commandline of a freshly setup ubuntu VM. I use Portainer ( A GUI tool for Docker containers) as a monitorung tool.

Myservice comes from a line from ur compose file:
```
services:
    app:
        image: lan2play/eventula-manager:latest
        restart: unless-stopped
        volumes:
        - eventula_manager_storage:/web/html/storage/
        expose:
        - "80"
        env_file:
        - ./.env
        container_name: eventula_manager_app
        labels:
        - "com.centurylinklabs.watchtower.scope=ev01"
        - "traefik.enable=true"
        - "traefik.http.routers.ev01.rule=Host(`${APP_URL}`)"
        - "traefik.http.routers.ev01.entrypoints=websecure"
        - "traefik.http.routers.ev01.tls.certresolver=le"
        - "traefik.http.services.myservice.loadbalancer.server.port=80"
```
**- "traefik.http.services._myservice_.loadbalancer.server.port=80"**

its an online machine.

I think its still try to boot, if im not wrong, i didn´t canceled it.
I´ll check the logs in a minute.

Best regards
Christian
